In [4]:
import torch
import numpy as np

tensor1 = torch.rand(2, 3, 4)
print("tensor1:")
print(tensor1)

np_array = np.ones((2, 4, 5), dtype = np.float32)
print("\nnumpy array:")
print(np_array)

tensor2 = torch.tensor(np_array)
print("\ntensor2 (converted from numpy)")
print(tensor2)

result = torch.bmm(tensor1, tensor2)
print("\nresult tensor:")
print(result)

print("\nresult tensor shape:", result.shape)
print("result tensor dtype", result.dtype)

tensor1:
tensor([[[0.5116, 0.9111, 0.2903, 0.6592],
         [0.0165, 0.9302, 0.2755, 0.6278],
         [0.5906, 0.9373, 0.1015, 0.9633]],

        [[0.8917, 0.6247, 0.9708, 0.3969],
         [0.3173, 0.6415, 0.9486, 0.4939],
         [0.1194, 0.5744, 0.7900, 0.6929]]])

numpy array:
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]

tensor2 (converted from numpy)
tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

result tensor:
tensor([[[2.3722, 2.3722, 2.3722, 2.3722, 2.3722],
         [1.8501, 1.8501, 1.8501, 1.8501, 1.8501],
         [2.5928, 2.5928, 2.5928, 2.5928, 2.5928]],

        [[2.8841, 2.8841, 2.8841, 2.8841, 2.8841],
         [2.4013, 2.4013, 2.4013, 2.4013, 2.4013],
  

In [5]:
import torch
import numpy as np

t1 = torch.rand(2, 3, 4)

n = np.ones((2, 4, 5), dtype = np.float32)

t2 = torch.from_numpy(n)

t3 = torch.matmul(t1, t2)

print(t3.shape)
print(t3.dtype)

torch.Size([2, 3, 5])
torch.float32
